apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-pipeline-production

namePrefix: prod-

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml

commonLabels:
  environment: production

commonAnnotations:
  app.kubernetes.io/environment: production
