apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-pipeline
  labels:
    app: gitops-pipeline
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: gitops-pipeline.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitops-pipeline
                port:
                  name: http
